<?php
/**
 * @file
 * A custom module to control the layout of the Municipality term pages
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function netstof_municipality_pages_help($path, $arg) {
  switch ($path) {
    case "admin/helt#netstof_municipality_pages":
      return '' . t("Municipality pages display helper module") . '';
      break;
  }
}
/*
 * Find the featured municipality pages by filtering on membership status field on the term
 */
function netstof_municipality_pages_page_build() {
  if (current_path() == 'node/569') {

    $query = "SELECT taxonomy_term_data.tid AS tid FROM {taxonomy_term_data} taxonomy_term_data
LEFT JOIN {taxonomy_vocabulary} taxonomy_vocabulary ON taxonomy_term_data.vid = taxonomy_vocabulary.vid
INNER JOIN {field_data_field_municipality_member} field_data_field_municipality_member ON taxonomy_term_data.tid = field_data_field_municipality_member.entity_id AND (field_data_field_municipality_member.entity_type = 'taxonomy_term' AND field_data_field_municipality_member.deleted = '0')
WHERE (( (taxonomy_vocabulary.machine_name IN  ('municipalities')) AND (field_data_field_municipality_member.field_municipality_member_value = '1') ))";

    $result = db_query($query)->fetchAll();
    foreach($result as $item) {
      $tids[] = $item->tid;
    }
    //Add the tids of the municipalities to a javascript array
    drupal_add_js(array('netstof_municipality_pages' => array('tids' => $tids)), array('type' => 'setting'));
  }
}

/*
 * Implementation of hook_form_alter()
 *
 * Add the js file that makes sure, the featured municipality pages are redirected
 */
function netstof_municipality_pages_form_alter(&$form, &$form_state, $form_id){
  $script = drupal_get_path('module', 'netstof_municipality_pages') . '/js/netstof_municipality_pages.js';
  if ($form_id == 'views_exposed_form' && ($form['#id'] == 'views-exposed-form-kort-default')) {
    $form['#attached']['js'][] = $script;
  }
}
